import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'

import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    // ADMIN MENU
    {
        key: 'adminMenu',
        path: '',
        title: 'QUẢN TRỊ',
        translateKey: 'nav.adminMenu',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: ['admin'],
        subMenu: [
            {
                key: 'admin.dashboard',
                path: '/admin/dashboard',
                title: 'Bảng điều khiển',
                translateKey: 'nav.admin.dashboard',
                icon: 'dashboard',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['admin'],
                subMenu: [],
            },
            {
                key: 'admin.users',
                path: '/admin/users',
                title: 'Người dùng',
                translateKey: 'nav.admin.users',
                icon: 'users',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['admin'],
                subMenu: [],
            },
            {
                key: 'admin.orders',
                path: '/admin/orders',
                title: 'Đơn hàng',
                translateKey: 'nav.admin.orders',
                icon: 'orders',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['admin'],
                subMenu: [],
            },
            {
                key: 'admin.services',
                path: '/admin/services',
                title: 'Dịch vụ',
                translateKey: 'nav.admin.services',
                icon: 'serviceList',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['admin'],
                subMenu: [],
            },
            {
                key: 'admin.finance',
                path: '/admin/finance',
                title: 'Tài chính',
                translateKey: 'nav.admin.finance',
                icon: 'wallet',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['admin'],
                subMenu: [],
            },
            {
                key: 'admin.settings',
                path: '/admin/settings',
                title: 'Cài đặt',
                translateKey: 'nav.admin.settings',
                icon: 'settings',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['admin'],
                subMenu: [],
            },
            {
                key: 'admin.support',
                path: '/admin/support',
                title: 'Hỗ trợ',
                translateKey: 'nav.admin.support',
                icon: 'support',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['admin'],
                subMenu: [],
            },
        ],
    },

    // MAIN MENU
    {
        key: 'mainMenu',
        path: '',
        title: 'MAIN MENU',
        translateKey: 'nav.mainMenu',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'dashboard',
                path: '/dashboard',
                title: 'Trang chủ',
                translateKey: 'nav.dashboard',
                icon: 'dashboard',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'wallet',
                path: '',
                title: 'Nạp Tiền',
                translateKey: 'nav.wallet',
                icon: 'wallet',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'wallet.bank',
                        path: '/wallet/deposit',
                        title: 'Nạp chuyển khoản',
                        translateKey: 'nav.wallet.bank',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'wallet.card',
                        path: '/wallet/card',
                        title: 'Nạp thẻ cào',
                        translateKey: 'nav.wallet.card',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'apiPartner',
                path: '/api-partner',
                title: 'API & Đối Tác',
                translateKey: 'nav.apiPartner',
                icon: 'api',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'otherServices',
                path: '/other-services',
                title: 'Dịch Vụ Khác',
                translateKey: 'nav.otherServices',
                icon: 'otherServices',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'support',
                path: '/support',
                title: 'Hỗ Trợ',
                translateKey: 'nav.support',
                icon: 'support',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'profile',
                path: '/profile',
                title: 'Trang cá nhân',
                translateKey: 'nav.profile',
                icon: 'user',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    // SẢN PHẨM
    {
        key: 'products',
        path: '',
        title: 'SẢN PHẨM',
        translateKey: 'nav.products',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'serviceList',
                path: '/services',
                title: 'Danh sách',
                translateKey: 'nav.serviceList',
                icon: 'serviceList',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'orderHistory',
                path: '/orders',
                title: 'Đơn hàng',
                translateKey: 'nav.orderHistory',
                icon: 'orders',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    // SỰ KIỆN
    {
        key: 'events',
        path: '',
        title: 'SỰ KIỆN',
        translateKey: 'nav.events',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'luckyWheel',
                path: '/lucky-wheel',
                title: 'Vòng Quay May Mắn',
                translateKey: 'nav.luckyWheel',
                icon: 'luckyWheel',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    // DỊCH VỤ - Platforms
    {
        key: 'platforms',
        path: '',
        title: 'DỊCH VỤ',
        translateKey: 'nav.platforms',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'bulkOrder',
                path: '/bulk-order',
                title: 'Đặt Nhiều Đơn',
                translateKey: 'nav.bulkOrder',
                icon: 'bulkOrder',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'unlockFacebook',
                path: '/services/unlock-facebook',
                title: 'Unlock Facebook 🔥',
                translateKey: 'nav.unlockFacebook',
                icon: 'unlockFb',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'facebook',
                path: '',
                title: 'Facebook',
                translateKey: 'nav.facebook',
                icon: 'facebook',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'facebook.likeViet',
                        path: '/services/facebook/like-viet',
                        title: 'Like Facebook | Việt 🇻🇳',
                        translateKey: 'nav.facebook.likeViet',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'facebook.likeTay',
                        path: '/services/facebook/like-tay',
                        title: 'Like Facebook | Tây 🌎',
                        translateKey: 'nav.facebook.likeTay',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'facebook.camxuc',
                        path: '/services/facebook/cam-xuc',
                        title: 'Cảm Xúc Facebook | Tây [Siêu Rẻ]🔥',
                        translateKey: 'nav.facebook.camxuc',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'facebook.camxucviet',
                        path: '/services/facebook/cam-xuc-viet',
                        title: 'Cảm Xúc Facebook Việt [Hạ]🔥',
                        translateKey: 'nav.facebook.camxucviet',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'facebook.comment',
                        path: '/services/facebook/comment',
                        title: 'Bình Luận',
                        translateKey: 'nav.facebook.comment',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'facebook.follow',
                        path: '/services/facebook/follow',
                        title: 'Follow | Việt 🇻🇳',
                        translateKey: 'nav.facebook.follow',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'tiktok',
                path: '',
                title: 'Tik Tok',
                translateKey: 'nav.tiktok',
                icon: 'tiktok',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'tiktok.like',
                        path: '/services/tiktok/like',
                        title: 'Like TikTok',
                        translateKey: 'nav.tiktok.like',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'tiktok.follow',
                        path: '/services/tiktok/follow',
                        title: 'Follow TikTok',
                        translateKey: 'nav.tiktok.follow',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'tiktok.view',
                        path: '/services/tiktok/view',
                        title: 'View TikTok',
                        translateKey: 'nav.tiktok.view',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'instagram',
                path: '',
                title: 'Instagram',
                translateKey: 'nav.instagram',
                icon: 'instagram',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'instagram.like',
                        path: '/services/instagram/like',
                        title: 'Like Instagram',
                        translateKey: 'nav.instagram.like',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'instagram.follow',
                        path: '/services/instagram/follow',
                        title: 'Follow Instagram',
                        translateKey: 'nav.instagram.follow',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'youtube',
                path: '',
                title: 'Youtube',
                translateKey: 'nav.youtube',
                icon: 'youtube',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'youtube.view',
                        path: '/services/youtube/view',
                        title: 'View YouTube',
                        translateKey: 'nav.youtube.view',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'youtube.like',
                        path: '/services/youtube/like',
                        title: 'Like YouTube',
                        translateKey: 'nav.youtube.like',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'youtube.subscribe',
                        path: '/services/youtube/subscribe',
                        title: 'Subscribe YouTube',
                        translateKey: 'nav.youtube.subscribe',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'telegram',
                path: '',
                title: 'Telegram',
                translateKey: 'nav.telegram',
                icon: 'telegram',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'telegram.member',
                        path: '/services/telegram/member',
                        title: 'Member Telegram',
                        translateKey: 'nav.telegram.member',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'threads',
                path: '',
                title: 'Threads',
                translateKey: 'nav.threads',
                icon: 'threads',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'threads.follow',
                        path: '/services/threads/follow',
                        title: 'Follow Threads',
                        translateKey: 'nav.threads.follow',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'twitter',
                path: '',
                title: 'Twitter',
                translateKey: 'nav.twitter',
                icon: 'twitter',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'twitter.follow',
                        path: '/services/twitter/follow',
                        title: 'Follow Twitter',
                        translateKey: 'nav.twitter.follow',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'discord',
                path: '',
                title: 'Discord',
                translateKey: 'nav.discord',
                icon: 'discord',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'discord.member',
                        path: '/services/discord/member',
                        title: 'Member Discord',
                        translateKey: 'nav.discord.member',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'shopee',
                path: '',
                title: 'Shopee',
                translateKey: 'nav.shopee',
                icon: 'shopee',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'shopee.follow',
                        path: '/services/shopee/follow',
                        title: 'Follow Shop Shopee',
                        translateKey: 'nav.shopee.follow',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'shopee.like',
                        path: '/services/shopee/like',
                        title: 'Like Sản Phẩm',
                        translateKey: 'nav.shopee.like',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
        ],
    },
]

export default navigationConfig
